<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
    <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
    <!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->
    <!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
    <!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->
    <OutputType>Exe</OutputType>
    <RootNamespace>ApocalypseNow</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- Display name -->
    <ApplicationTitle>ApocalypseNow</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.mortens.apocalypsenow</ApplicationId>
    <!-- Versions -->
    <MajorVersion>1</MajorVersion>
    <MinorVersion>5</MinorVersion>
    <BuildNumber>0</BuildNumber>
    <PatchNumber>0</PatchNumber>
    <FileVersion>$(MajorVersion).$(MinorVersion).$(BuildNumber).$(PatchNumber)</FileVersion>
    <AssemblyVersion>$(FileVersion)</AssemblyVersion>
    <ApplicationDisplayVersion>$(MajorVersion).$(MinorVersion).$(BuildNumber)</ApplicationDisplayVersion>
    <PackageVersion>$(ApplicationDisplayVersion)</PackageVersion>
    <ApplicationVersion>$(MajorVersion)</ApplicationVersion>
    <WarningLevel>9999</WarningLevel>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <Company>Mortens</Company>
    <Authors>Mortens</Authors>
    <IncludeSymbols>True</IncludeSymbols>
    <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
    <WindowsPackageType>MSIX</WindowsPackageType>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetBorderwork)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetBorderwork)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetBorderwork)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetBorderwork)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetBorderwork)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetBorderwork)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.png" Color="#000000" BaseSize="128,128" />
    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.120" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.10" />
    <PackageReference Include="Mtf.Maui.Controls" Version="2.0.40" />
    <PackageReference Include="Mtf.MAUI.LanguageService" Version="1.0.40" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="System.Formats.Nrbf" Version="9.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\Images\" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyAlias>h4ckw1thm3</AndroidSigningKeyAlias>
    <AndroidSigningKeyStore>C:\Work\KeyStore\H4ckW1thM3\keystore.jks</AndroidSigningKeyStore>
    <AndroidSigningKeyPass>file:C:\Work\KeyStore\H4ckW1thM3\AndroidSigningKeyPass.txt</AndroidSigningKeyPass>
    <AndroidSigningStorePass>file:C:\Work\KeyStore\H4ckW1thM3\AndroidSigningStorePass.txt</AndroidSigningStorePass>
    <AndroidPackageFormats>aab;apk</AndroidPackageFormats>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Views\SurvivalGuidesPage.xaml.cs">
      <DependentUpon>SurvivalGuidesPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <MauiXaml Update="Views\AITakeoverPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\ApocalypseChecklistPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\SurvivalGuidesPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\BagPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\ChemicalPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\ClimateChangePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\CyberCatastrophePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\EarthquakePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\EconomicCrisisPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\ExplosionPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\ExtremeWeatherPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\FloodingPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\GeneralView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\HeatwavesPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\HurricanePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\InternetOutagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\MeteorPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\NetworkOutagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\NuclearPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\PandemicPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\PowerOutagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\ShortagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\TsunamiPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\VolcanoPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\WarPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\WildfirePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Views\WinterStormPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>
  <ItemGroup>
    <None Update="Views\AITakeoverPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\ChemicalPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\ClimateChangePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\CyberCatastrophePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\EarthquakePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\EconomicCrisisPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\ExplosionPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\ExtremeWeatherPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\FloodingPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\GeneralView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\HeatwavesPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\HurricanePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\InternetOutagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\MeteorPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\NetworkOutagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\NuclearPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\PandemicPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\PowerOutagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\ShortagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\TsunamiPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\VolcanoPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\WarPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\WildfirePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\WinterStormPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
</Project>